version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: embarkx
      POSTGRES_PASSWORD: embarkx
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres # Renamed
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-afiya@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-afiyakhalid}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres # Renamed
    restart: unless-stopped
    depends_on:
      - postgres

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - postgres # Renamed

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - postgres # Renamed

  servicereg:
    image: afiyakhalid/servicereg
    container_name: servicereg
    ports:
      - "8761:8761"
    networks:
      - postgres # Renamed

  config-server-ms:
    image: afiyakhalid/configserver
    container_name: config-server-ms
    ports:
      - "8088:8088"
    depends_on:
      - servicereg
    networks:
      - postgres # Renamed
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

  companyms:
    image: afiyakhalid/companyms
    container_name: companyms
    ports:
      - "8081:8081"
    depends_on:
      - servicereg
      - config-server-ms
      - postgres
      - rabbitmq
    networks:
      - postgres # Renamed
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

  jobms:
    image: afiyakhalid/jobms
    container_name: jobms
    ports:
      - "8082:8082"
    depends_on:
      - servicereg
      - config-server-ms
      - postgres
      - rabbitmq
    networks:
      - postgres # Renamed
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

  reviewms:
    image: afiyakhalid/reviewms
    container_name: reviewms
    ports:
      - "8083:8083"
    depends_on:
      - servicereg
      - config-server-ms
      - postgres
      - rabbitmq
    networks:
      - postgres # Renamed
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

  apigateway:
    image: afiyakhalid/apigateway
    container_name: apigateway
    ports:
      - "8084:8084"
    depends_on:
      - servicereg
      - config-server-ms
    networks:
      - postgres # Renamed
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

networks:
  postgres: # Renamed the network definition
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:

